version: '3.9'

services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - CELERY_BROKER_URL=redis://host.docker.internal:6379/0
      - CELERY_RESULT_BACKEND=redis://host.docker.internal:6379/0
    volumes:
      - .:/app
      - ./media:/app/media/
      - ./incoming_files:/app/incoming_files/
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - worker

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A core worker -l info
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - CELERY_BROKER_URL=redis://host.docker.internal:6379/0
      - CELERY_RESULT_BACKEND=redis://host.docker.internal:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis

  file-watcher:
    build: .
    command: python /app/watcher.py
    volumes:
      - ./incoming_files:/app/incoming_files
    depends_on:
      - web
