# Generated by Django 4.1.7 on 2023-02-25 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_id", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("RUNNING", "Running"), ("COMPLETED", "Completed")],
                        default="Running",
                        max_length=255,
                    ),
                ),
                (
                    "csv_file",
                    models.FileField(blank=True, null=True, upload_to="reports/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "store_id",
                    models.IntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "timezone_str",
                    models.CharField(default="America/Chicago", max_length=50),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoreStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        max_length=10,
                    ),
                ),
                ("timestamp_utc", models.DateTimeField()),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.store"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoreReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uptime_last_hour", models.IntegerField(default=0)),
                ("uptime_last_day", models.IntegerField(default=0)),
                ("uptime_last_week", models.IntegerField(default=0)),
                ("downtime_last_hour", models.IntegerField(default=0)),
                ("downtime_last_day", models.IntegerField(default=0)),
                ("downtime_last_week", models.IntegerField(default=0)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.report"
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.store"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoreHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time_local", models.TimeField()),
                ("end_time_local", models.TimeField()),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.store"
                    ),
                ),
            ],
        ),
    ]
